name: Perf Test

on:
  workflow_dispatch:
    inputs:
      threadCount:
        description: "Number of threads (users)"
        required: false
        default: "4"

jobs:
  perf-test:
    runs-on: [self-hosted, test-02]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure JMX
        run: |
          echo "Setting threadCount to: ${{ github.event.inputs.threadCount }}"
          xmlstarlet ed -L -u '//stringProp[@name="ThreadGroup.num_threads"]' -v '${{ github.event.inputs.threadCount }}' src/test/jmeter/perf.jmx
          echo "Current threads num: $(xmlstarlet sel -t -v '//stringProp[@name="ThreadGroup.num_threads"]' src/test/jmeter/perf.jmx)"

      - name: Run JMeter Test
        run: |
          mvn -q package
          mvn -q jmeter:jmeter@configuration2 -DjmeterTest=perf.jmx

      - name: Archive results
        run: |
          TIMESTAMP=$(TZ='Asia/Shanghai' date '+%Y%m%d-%H%M')
          FOLDER_NAME="${TIMESTAMP}-${{ github.event.inputs.threadCount }}threads"
          mv target/jmeter "$FOLDER_NAME"
          tar -czf "${FOLDER_NAME}.tar.gz" "$FOLDER_NAME"
          echo "ARCHIVE_NAME=${FOLDER_NAME}.tar.gz" >> $GITHUB_ENV
          echo "RESULT_NAME=${FOLDER_NAME}" >> $GITHUB_ENV

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RESULT_NAME }}
          path: ${{ env.ARCHIVE_NAME }}

  count-channels:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [perf-test]
    steps:
      - name: Count channels
        run: bash count_channels.sh
