name: Run Fiber Testnet Nodes

on:
  workflow_dispatch:
    inputs:
      fiber_version:
        description: "Fiber version"
        required: false
        default: "develop"
      open_channel_count:
        description: "Open channel count"
        required: false
        default: "1"

  workflow_call:
    inputs:
      fiber_version:
        type: string
        required: false
        default: "develop"
      open_channel_count:
        type: string
        required: false
        default: "1"

jobs:
  shutdown-channel-test-03:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz
    steps:
      - name: Shutdown Channel
        run: |
          if [ ! -d "fiber-stability-test-nodes" ]; then
            echo "Directory fiber-stability-test-nodes does not exist"
          else
            cd fiber-stability-test-nodes/remote
            bash 5_shutdown_channel.sh
          fi
          sleep 30

  shutdown-channel-test-04:
    runs-on: [self-hosted, test-04]
    defaults:
      run:
        working-directory: /home/ckb/scz
    steps:
      - name: Shutdown Channel
        run: |
          if [ ! -d "fiber-stability-test-nodes" ]; then
            echo "Directory fiber-stability-test-nodes does not exist"
          else
            cd fiber-stability-test-nodes/remote
            bash 5_shutdown_channel.sh
          fi
          sleep 30

  run-on-test-03:
    if: always()
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz
    needs: [shutdown-channel-test-03, shutdown-channel-test-04]
    steps:
      - name: Fund addresses
        run: |
          pkill fnn || true
          rm -rf fiber-stability-test-nodes
          git clone https://github.com/sunchengzhu/fiber-stability-test-nodes.git
          cd fiber-stability-test-nodes
          /opt/gradle/gradle-8.5/bin/gradle wrapper
          ./gradlew run
      - name: Prepare
        run: |
          cd fiber-stability-test-nodes/remote
          bash 1_prepare.sh "${{ github.event.inputs.fiber_version }}"
      - name: Run
        run: |
          sudo systemctl start fnn.service
          sleep 30
          sudo journalctl -u fnn.service --since "1 minutes ago"

  run-on-test-04:
    if: always()
    runs-on: [self-hosted, test-04]
    defaults:
      run:
        working-directory: /home/ckb/scz
    needs: [shutdown-channel-test-03, shutdown-channel-test-04]
    steps:
      - name: Clone fiber-stability-test-nodes
        run: |
          pkill fnn || true
          rm -rf fiber-stability-test-nodes
          git clone https://github.com/sunchengzhu/fiber-stability-test-nodes.git
      - name: Prepare
        run: |
          cd fiber-stability-test-nodes/remote
          bash 1_prepare.sh "${{ github.event.inputs.fiber_version }}"
      - name: Run
        run: |
          sudo systemctl start fnn.service
          sleep 10
          sudo journalctl -u fnn.service --since "1 minutes ago"

  run-on-test-05:
    if: always()
    runs-on: [self-hosted, test-05]
    defaults:
      run:
        working-directory: /home/ckb/scz
    needs: [shutdown-channel-test-03, shutdown-channel-test-04]
    steps:
      - name: Clone fiber-stability-test-nodes
        run: |
          pkill fnn || true
          rm -rf fiber-stability-test-nodes
          git clone https://github.com/sunchengzhu/fiber-stability-test-nodes.git
      - name: Prepare
        run: |
          cd fiber-stability-test-nodes/remote
          bash 1_prepare.sh "${{ github.event.inputs.fiber_version }}"
      - name: Run
        run: |
          sudo systemctl start fnn.service
          sleep 10
          sudo journalctl -u fnn.service --since "1 minutes ago"

  connect-peer-test-03:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [run-on-test-03, run-on-test-04, run-on-test-05]
    steps:
      - name: Connect Peer
        run: bash 3_connect_peer.sh

  connect-peer-test-04:
    runs-on: [self-hosted, test-04]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [run-on-test-03, run-on-test-04, run-on-test-05]
    steps:
      - name: Connect Peer
        run: bash 3_connect_peer.sh

  open-channel-test-03:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [connect-peer-test-03, connect-peer-test-04]
    steps:
      - name: Open channel
        run: |
          bash 4_open_channel.sh "${{ github.event.inputs.open_channel_count }}"
          bash count_channels.sh

  open-channel-test-04:
    runs-on: [self-hosted, test-04]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [connect-peer-test-03, connect-peer-test-04, open-channel-test-03]
    steps:
      - name: Open channel
        run: |
          bash 4_open_channel.sh "${{ github.event.inputs.open_channel_count }}"
          bash count_channels.sh

  # open-channel-test-05:
  #   runs-on: [self-hosted, test-05]
  #   defaults:
  #     run:
  #       working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
  #   needs: [connect-peer-test-03, connect-peer-test-04, open-channel-test-04]
  #   steps:
  #     - name: Open channel
  #       run: |
  #         bash 4_open_channel.sh
  #         bash count_channels.sh

  check-channels:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz/fiber-stability-test-nodes/remote
    needs: [open-channel-test-03, open-channel-test-04]
    steps:
      - name: Test a to g
        run: |
          bash 6_test_a_to_g.sh
          bash count_channels.sh
