name: Test Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  run-on-test-03:
    runs-on: [self-hosted, test-03]
    defaults:
      run:
        working-directory: /home/ckb/scz
    steps:
      - name: Fund addresses
        run: |
          pkill fnn || true
          rm -rf fiber-stability-test-nodes
          git clone https://github.com/sunchengzhu/fiber-stability-test-nodes.git
          cd fiber-stability-test-nodes
          /opt/gradle/gradle-8.5/bin/gradle wrapper
          ./gradlew run
  run-on-test-04:
    runs-on: [self-hosted, test-04]
    defaults:
      run:
        working-directory: /home/ckb/scz
    steps:
      - name: Check working directory
        run: pwd

  run-on-test-05:
    runs-on: [self-hosted, test-05]
    defaults:
      run:
        working-directory: /home/ckb/scz
    steps:
      - name: Check working directory
        run: pwd
