name: Test Self-hosted Runner

on:
  push:
    branches:
      - main  # 或者你可以选择任何合适的分支
  workflow_dispatch:  # 允许手动触发

jobs:
  test-command:
    runs-on: self-hosted  # 使用自托管的 Runner

    steps:
      - name: Check working directory
        run: pwd